### ISSUE TITLE
Add formatting for more visually parseable messages

### ISSUE THREAD

**Issue by nornagon** [etcinit/phabulous#30] opened 2016-03-22 16:05 UTC
The messages phabulous sends are difficult to visually parse. Instead of:

<p><p>
person closed D4281: Add things to the thing by committing rTd74ade4cded6: Add things to the thing. ([More info]())
otherperson updated the test plan for D4311: Fix some things. ([More info]())

<p><p>
Adding some variation in formatting makes it easier to focus on the different parts of the message (what was done, who did it, what did they do it to):

<p><p>
**person** closed **D4281: Add things to the thing** by committing **rTd74ade4cded6: Add things to the thing**. ([More info]())
**otherperson** updated the test plan for **D4311: Fix some things**. ([More info]())

**Comment by schemar** [comment] 2018-03-12 18:53
Closing this as duplicate of #48

**Closed by schemar** 2018-03-12 18:53 UTC
Labels: enhancement, help wanted
